# -*- coding: utf-8 -*-
"""Copy of parkinsons_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzvq1iA7_uuhD5ePsZo8CEkeT4IsnBNE
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# ============================================================================
# 1. DOPAMINE KINETICS IN THE BRAIN
# ============================================================================
# Model: d[D]/dt = k_synth - k_deg * [D]
# Steady-state: [D_ss] = k_synth / k_deg

def dopamine_kinetics(D, t, k_synth, k_deg):
    """Simple dopamine turnover model"""
    dD_dt = k_synth - k_deg * D
    return dD_dt

# Parameters (arbitrary units, scaled for visualization)
k_synth_healthy = 1.0      # synthesis rate (healthy)
k_synth_parkinsons = 0.3   # synthesis rate (Parkinson's - fewer neurons)
k_deg = 0.5                # degradation rate

# Initial dopamine level
D0 = 0

# Time (hours)
t_dopamine = np.linspace(0, 10, 200)

# Solve ODE for healthy vs Parkinson's
D_healthy = odeint(dopamine_kinetics, D0, t_dopamine, args=(k_synth_healthy, k_deg))
D_parkinsons = odeint(dopamine_kinetics, D0, t_dopamine, args=(k_synth_parkinsons, k_deg))

# Calculate steady-state levels
D_ss_healthy = k_synth_healthy / k_deg
D_ss_parkinsons = k_synth_parkinsons / k_deg

# ============================================================================
# 2. LEVODOPA PHARMACOKINETICS
# ============================================================================
# Model: C(t) = C0 * exp(-k_elim * t)
# Half-life: t_1/2 = ln(2) / k_elim

# L-DOPA parameters
t_half_ldopa = 1.0  # hours (realistic: ~60 min)
k_elim_ldopa = np.log(2) / t_half_ldopa

C0_ldopa = 10.0  # initial plasma concentration (arbitrary units)

# Simulate L-DOPA without and with COMT/MAO-B inhibitor
t_pharma = np.linspace(0, 8, 200)
C_ldopa_alone = C0_ldopa * np.exp(-k_elim_ldopa * t_pharma)

# With inhibitor: slower elimination (longer half-life)
t_half_with_inhibitor = 1.5  # hours
k_elim_with_inhibitor = np.log(2) / t_half_with_inhibitor
C_ldopa_with_inhibitor = C0_ldopa * np.exp(-k_elim_with_inhibitor * t_pharma)

# ============================================================================
# 3. TREATMENT EFFICACY DECLINE OVER TIME
# ============================================================================
# Model: E(t) = E0 * exp(-lambda * t)
# Where t is years of therapy, lambda is "neuronal loss rate"

years_of_therapy = np.linspace(0, 35, 100)
E0 = 100  # Initial efficacy (%)
lambda_decline = 0.06  # Rate of decline per year (fitted concept)

treatment_efficacy = E0 * np.exp(-lambda_decline * years_of_therapy)

# Add DBS intervention around year 20
dbs_year = 20
efficacy_with_dbs = np.where(
    years_of_therapy < dbs_year,
    E0 * np.exp(-lambda_decline * years_of_therapy),
    70 + 30 * np.exp(-lambda_decline * (years_of_therapy - dbs_year))
)

# ============================================================================
# 4. PULSATILE DOPAMINE RELEASE (ON-OFF PHENOMENA)
# ============================================================================
# Simulate medication timing: doses every 4 hours, but declining response

dosing_times = np.array([0, 4, 8, 12, 16, 20, 24])
t_detailed = np.linspace(0, 26, 500)

dopamine_pulsatile = np.zeros_like(t_detailed)
dose_response_factor = 1.0  # Will decrease with each dose

for i, dose_time in enumerate(dosing_times):
    # Each dose produces a bell curve, but amplitude decreases
    dose_amplitude = 8 * (0.85 ** i)  # Declining response over time
    dose_width = 1.5
    dopamine_pulsatile += dose_amplitude * np.exp(-((t_detailed - dose_time) ** 2) / (2 * dose_width ** 2))

# ============================================================================
# PLOTTING
# ============================================================================

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Parkinson\'s Disease: Dopamine & Levodopa Kinetics', fontsize=16, fontweight='bold')

# Plot 1: Dopamine Kinetics (Healthy vs Parkinson's)
ax1 = axes[0, 0]
ax1.plot(t_dopamine, D_healthy.flatten(), 'g-', linewidth=2.5, label='Healthy Brain')
ax1.plot(t_dopamine, D_parkinsons.flatten(), 'r-', linewidth=2.5, label="Parkinson's (fewer neurons)")
ax1.axhline(D_ss_healthy, color='g', linestyle='--', alpha=0.5, label=f'Steady-state (healthy): {D_ss_healthy:.2f}')
ax1.axhline(D_ss_parkinsons, color='r', linestyle='--', alpha=0.5, label=f'Steady-state (PD): {D_ss_parkinsons:.2f}')
ax1.set_xlabel('Time (hours)', fontsize=11)
ax1.set_ylabel('Dopamine Concentration [D]', fontsize=11)
ax1.set_title('Section 2: Dopamine Turnover\nd[D]/dt = k_synth - k_deg·[D]', fontsize=12, fontweight='bold')
ax1.legend(fontsize=9)
ax1.grid(True, alpha=0.3)

# Plot 2: L-DOPA Pharmacokinetics
ax2 = axes[0, 1]
ax2.plot(t_pharma, C_ldopa_alone, 'b-', linewidth=2.5, label=f'L-DOPA alone (t₁/₂ = {t_half_ldopa:.1f}h)')
ax2.plot(t_pharma, C_ldopa_with_inhibitor, 'purple', linewidth=2.5, label=f'With COMT/MAO-B inhibitor (t₁/₂ = {t_half_with_inhibitor:.1f}h)')
ax2.axhline(C0_ldopa / 2, color='gray', linestyle=':', alpha=0.5, label='50% (Half-life)')
ax2.set_xlabel('Time (hours)', fontsize=11)
ax2.set_ylabel('Plasma [L-DOPA] Concentration', fontsize=11)
ax2.set_title('Section 3: L-DOPA Pharmacokinetics\nC(t) = C₀·e^(-k_elim·t)', fontsize=12, fontweight='bold')
ax2.legend(fontsize=9)
ax2.grid(True, alpha=0.3)

# Plot 3: Treatment Efficacy Decline Over Time
ax3 = axes[1, 0]
ax3.plot(years_of_therapy, treatment_efficacy, 'orange', linewidth=2.5, label='Without intervention')
ax3.plot(years_of_therapy, efficacy_with_dbs, 'g-', linewidth=2.5, label='With DBS (year 20)')
ax3.axvline(dbs_year, color='green', linestyle='--', alpha=0.5, linewidth=2)
ax3.fill_between(years_of_therapy, treatment_efficacy, alpha=0.2, color='orange')
ax3.fill_between(years_of_therapy, efficacy_with_dbs, alpha=0.2, color='green')
ax3.set_xlabel('Years of Therapy', fontsize=11)
ax3.set_ylabel('Treatment Efficacy (%)', fontsize=11)
ax3.set_title('Section 4: Efficiency Decline Over Time\nE(t) = E₀·e^(-λ·t)', fontsize=12, fontweight='bold')
ax3.legend(fontsize=9)
ax3.grid(True, alpha=0.3)
ax3.set_ylim([0, 105])

# Plot 4: Pulsatile Dopamine (ON-OFF Phenomena)
ax4 = axes[1, 1]
ax4.plot(t_detailed, dopamine_pulsatile, 'darkred', linewidth=2.5)
ax4.fill_between(t_detailed, dopamine_pulsatile, alpha=0.3, color='darkred')
ax4.scatter(dosing_times, [dopamine_pulsatile[np.argmin(np.abs(t_detailed - dt))] for dt in dosing_times],
            color='red', s=100, zorder=5, label='Medication doses (4h interval)')
ax4.axhline(3, color='gray', linestyle='--', alpha=0.5, label='Symptom threshold')
ax4.set_xlabel('Time (hours)', fontsize=11)
ax4.set_ylabel('Dopamine Release', fontsize=11)
ax4.set_title('Section 4: Pulsatile Release & "On-Off" Phenomena\n(Declining response per dose)', fontsize=12, fontweight='bold')
ax4.legend(fontsize=9)
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('parkinsons_kinetics.png', dpi=300, bbox_inches='tight')
plt.show()

print("=" * 70)
print("PARKINSON'S DISEASE KINETIC MODEL SUMMARY")
print("=" * 70)
print(f"\n1. DOPAMINE KINETICS")
print(f"   Healthy steady-state [D]: {D_ss_healthy:.3f}")
print(f"   Parkinson's steady-state [D]: {D_ss_parkinsons:.3f}")
print(f"   Reduction: {(1 - D_ss_parkinsons/D_ss_healthy)*100:.1f}%")
print(f"\n2. L-DOPA HALF-LIFE")
print(f"   Without inhibitor: {t_half_ldopa} hour(s)")
print(f"   With COMT/MAO-B inhibitor: {t_half_with_inhibitor} hour(s)")
print(f"   Duration extension: {(t_half_with_inhibitor/t_half_ldopa - 1)*100:.1f}%")
print(f"\n3. TREATMENT EFFICACY DECLINE")
print(f"   Initial efficacy: {E0}%")
print(f"   Decay rate (λ): {lambda_decline} per year")
print(f"   Efficacy at year 10: {E0 * np.exp(-lambda_decline * 10):.1f}%")
print(f"   Efficacy at year 20 (pre-DBS): {E0 * np.exp(-lambda_decline * 20):.1f}%")
print(f"   Efficacy at year 20 (with DBS): 70%")
print(f"   Efficacy at year 35: {efficacy_with_dbs[-1]:.1f}%")
print(f"\n4. PULSATILE DOPAMINE")
print(f"   Dosing interval: 4 hours")
print(f"   Initial peak amplitude: {dopamine_pulsatile.max():.2f}")
print(f"   Amplitude decline reflects receptor desensitization & storage capacity loss")
print("=" * 70)