# -*- coding: utf-8 -*-
"""Copy of Parkinson_2_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1039K0cu-xAkVtdY7wdoe5S0io4BlNcFA
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from scipy.signal import find_peaks
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# ============================================================================
# 1. DOPAMINE KINETICS IN THE BRAIN
# ============================================================================
def dopamine_kinetics(D, t, k_synth, k_deg):
    """Simple dopamine turnover model"""
    dD_dt = k_synth - k_deg * D
    return dD_dt

k_synth_healthy = 1.0
k_synth_parkinsons = 0.3
k_deg = 0.5

D0 = 0
t_dopamine = np.linspace(0, 10, 200)

D_healthy = odeint(dopamine_kinetics, D0, t_dopamine, args=(k_synth_healthy, k_deg))
D_parkinsons = odeint(dopamine_kinetics, D0, t_dopamine, args=(k_synth_parkinsons, k_deg))

D_ss_healthy = k_synth_healthy / k_deg
D_ss_parkinsons = k_synth_parkinsons / k_deg

# ============================================================================
# 2. LEVODOPA PHARMACOKINETICS (with & without COMT inhibitors)
# ============================================================================

t_pharma = np.linspace(0, 12, 300)

# L-DOPA alone: fast elimination
t_half_ldopa = 1.0
k_elim_ldopa = np.log(2) / t_half_ldopa
C0_ldopa = 10.0
C_ldopa_alone = C0_ldopa * np.exp(-k_elim_ldopa * t_pharma)

# With COMT inhibitor: slower elimination
t_half_with_comt = 2.5
k_elim_with_comt = np.log(2) / t_half_with_comt
C_ldopa_with_comt = C0_ldopa * np.exp(-k_elim_with_comt * t_pharma)

# Calculate oscillation metric: peak-to-trough variance
def calculate_oscillation(C):
    """Measure oscillation intensity (0 = smooth, 1 = highly pulsatile)"""
    peaks, _ = find_peaks(C, height=np.max(C) * 0.3)
    if len(peaks) < 2:
        return 0
    peak_heights = C[peaks]
    oscillation = np.std(peak_heights) / np.mean(peak_heights) if np.mean(peak_heights) > 0 else 0
    return oscillation

# ============================================================================
# 3. CONTINUOUS INFUSION PUMP vs PULSATILE DOSING
# ============================================================================

t_infusion = np.linspace(0, 24, 500)

# Pulsatile: 4 doses of L-DOPA
dosing_times_pulsatile = np.array([0, 6, 12, 18])
C_pulsatile = np.zeros_like(t_infusion)
for dose_time in dosing_times_pulsatile:
    dose_amplitude = 10.0
    dose_width = 0.8
    C_pulsatile += dose_amplitude * np.exp(-((t_infusion - dose_time) ** 2) / (2 * dose_width ** 2))

# Continuous infusion: constant delivery
C_continuous_infusion = np.ones_like(t_infusion) * 6.0 + 0.5 * np.random.normal(0, 1, len(t_infusion))
C_continuous_infusion = np.convolve(C_continuous_infusion, np.ones(10)/10, mode='same')  # Smooth

# ============================================================================
# 4. RECEPTOR DESENSITIZATION & STORAGE CAPACITY LOSS
# ============================================================================
# Model: Available dopamine storage decreases over time
# Receptor sensitivity also decreases (downregulation)

years_therapy = np.linspace(0, 35, 100)

# Storage capacity decline
storage_capacity = 100 * np.exp(-0.08 * years_therapy)

# Receptor sensitivity decline (desensitization)
receptor_sensitivity = 100 * np.exp(-0.05 * years_therapy)

# Effective dopamine response = actual dopamine * storage * sensitivity
effective_response = 100 * np.exp(-0.08 * years_therapy) * np.exp(-0.05 * years_therapy)

# With adjunct therapy (MAO-B inhibitors): slower decline
receptor_sensitivity_with_mao = 100 * np.exp(-0.02 * years_therapy)
effective_response_with_mao = 100 * np.exp(-0.08 * years_therapy) * np.exp(-0.02 * years_therapy)

# ============================================================================
# 5. PULSATILE DOPAMINE SIMULATION (declining response over time)
# ============================================================================

t_detailed = np.linspace(0, 26, 500)
dopamine_pulsatile_early = np.zeros_like(t_detailed)
dopamine_pulsatile_late = np.zeros_like(t_detailed)

dosing_times = np.array([0, 4, 8, 12, 16, 20, 24])

# Early therapy: good response
for i, dose_time in enumerate(dosing_times):
    dose_amplitude = 8 * (0.90 ** i)
    dose_width = 1.5
    dopamine_pulsatile_early += dose_amplitude * np.exp(-((t_detailed - dose_time) ** 2) / (2 * dose_width ** 2))

# Late therapy: poor response
for i, dose_time in enumerate(dosing_times):
    dose_amplitude = 3 * (0.75 ** i)  # Lower amplitude, faster decay
    dose_width = 1.2
    dopamine_pulsatile_late += dose_amplitude * np.exp(-((t_detailed - dose_time) ** 2) / (2 * dose_width ** 2))

# ============================================================================
# 6. MINI ML MODEL: Predicting Symptom Scores from Treatment Variables
# ============================================================================

# Synthetic training data: years on therapy, dosage (mg), age, symptom score
np.random.seed(42)
n_samples = 50

years_on_therapy = np.random.uniform(1, 30, n_samples)
dosage_mg = 200 + years_on_therapy * 100 + np.random.normal(0, 50, n_samples)  # Dosage increases over time
age = 50 + years_on_therapy * 0.3 + np.random.normal(0, 5, n_samples)

# Symptom score: depends on years (disease progression) and dosage (treatment effect)
# Higher score = worse symptoms
symptom_score = (
    30 +                                          # baseline
    years_on_therapy * 1.5 +                      # disease progression
    0.01 * dosage_mg +                            # medication burden
    0.3 * age +                                   # age effect
    np.random.normal(0, 5, n_samples)             # noise
)
symptom_score = np.clip(symptom_score, 0, 100)

# Features and target
X = np.column_stack([years_on_therapy, dosage_mg, age])
y = symptom_score

# Polynomial regression (degree 2) for non-linear relationship
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)
model = LinearRegression()
model.fit(X_poly, y)

# Predictions for visualization
years_range = np.linspace(1, 30, 50)
dosage_range = 200 + years_range * 100
age_range = 50 + years_range * 0.3
X_pred = np.column_stack([years_range, dosage_range, age_range])
X_pred_poly = poly.transform(X_pred)
y_pred = model.predict(X_pred_poly)

# Model R² score
from sklearn.metrics import r2_score
y_train_pred = model.predict(X_poly)
r2 = r2_score(y, y_train_pred)

# ============================================================================
# PLOTTING
# ============================================================================

fig = plt.figure(figsize=(18, 12))
gs = fig.add_gridspec(3, 3, hspace=0.3, wspace=0.3)

fig.suptitle('Advanced Parkinson\'s Disease Kinetics & ML Model', fontsize=18, fontweight='bold')

# ========== Row 1: Dopamine & COMT Inhibitors ==========

# Plot 1a: Dopamine Kinetics
ax1a = fig.add_subplot(gs[0, 0])
ax1a.plot(t_dopamine, D_healthy.flatten(), 'g-', linewidth=2.5, label='Healthy')
ax1a.plot(t_dopamine, D_parkinsons.flatten(), 'r-', linewidth=2.5, label="Parkinson's")
ax1a.set_xlabel('Time (hours)', fontsize=10)
ax1a.set_ylabel('Dopamine [D]', fontsize=10)
ax1a.set_title('Dopamine Turnover', fontsize=11, fontweight='bold')
ax1a.legend(fontsize=9)
ax1a.grid(True, alpha=0.3)

# Plot 1b: COMT Inhibitor Effect
ax1b = fig.add_subplot(gs[0, 1])
ax1b.plot(t_pharma, C_ldopa_alone, 'b-', linewidth=2.5, label=f'L-DOPA alone (t₁/₂ = {t_half_ldopa}h)')
ax1b.plot(t_pharma, C_ldopa_with_comt, 'purple', linewidth=2.5, label=f'+ COMT inhibitor (t₁/₂ = {t_half_with_comt}h)')
ax1b.fill_between(t_pharma, C_ldopa_alone, alpha=0.15, color='blue')
ax1b.fill_between(t_pharma, C_ldopa_with_comt, alpha=0.15, color='purple')
ax1b.axhline(C0_ldopa / 2, color='gray', linestyle=':', alpha=0.5)
ax1b.set_xlabel('Time (hours)', fontsize=10)
ax1b.set_ylabel('[L-DOPA]', fontsize=10)
ax1b.set_title('COMT Inhibitors: Extended Half-Life', fontsize=11, fontweight='bold')
ax1b.legend(fontsize=9)
ax1b.grid(True, alpha=0.3)

# Plot 1c: Oscillation Reduction
ax1c = fig.add_subplot(gs[0, 2])
osc_alone = calculate_oscillation(C_ldopa_alone)
osc_with_comt = calculate_oscillation(C_ldopa_with_comt)
treatments = ['L-DOPA\nAlone', 'L-DOPA +\nCOMT Inhibitor']
oscillations = [osc_alone, osc_with_comt]
colors_osc = ['blue', 'purple']
bars = ax1c.bar(treatments, oscillations, color=colors_osc, alpha=0.7, edgecolor='black', linewidth=1.5)
ax1c.set_ylabel('Oscillation Index', fontsize=10)
ax1c.set_title('Reduced Plasma Oscillations', fontsize=11, fontweight='bold')
ax1c.set_ylim([0, max(oscillations) * 1.3])
for bar, osc in zip(bars, oscillations):
    height = bar.get_height()
    ax1c.text(bar.get_x() + bar.get_width()/2., height,
              f'{osc:.3f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
ax1c.grid(True, alpha=0.3, axis='y')

# ========== Row 2: Continuous Infusion & Receptor Desensitization ==========

# Plot 2a: Pulsatile vs Continuous Infusion
ax2a = fig.add_subplot(gs[1, 0:2])
ax2a.plot(t_infusion, C_pulsatile, 'r-', linewidth=2, label='Pulsatile (4 doses/day)', alpha=0.8)
ax2a.plot(t_infusion, C_continuous_infusion, 'g-', linewidth=2.5, label='Continuous Infusion Pump')
ax2a.fill_between(t_infusion, C_pulsatile, alpha=0.15, color='red')
ax2a.fill_between(t_infusion, C_continuous_infusion, alpha=0.15, color='green')
ax2a.set_xlabel('Time (hours)', fontsize=10)
ax2a.set_ylabel('[L-DOPA]', fontsize=10)
ax2a.set_title('Continuous Infusion Pump: Smooth Dopamine Delivery', fontsize=11, fontweight='bold')
ax2a.legend(fontsize=10, loc='upper right')
ax2a.grid(True, alpha=0.3)

# Plot 2b: Receptor Desensitization & Storage Capacity
ax2b = fig.add_subplot(gs[1, 2])
ax2b.plot(years_therapy, storage_capacity, 'orange', linewidth=2.5, label='Storage Capacity')
ax2b.plot(years_therapy, receptor_sensitivity, 'red', linewidth=2.5, label='Receptor Sensitivity')
ax2b.plot(years_therapy, effective_response, 'darkred', linewidth=2.5, linestyle='--', label='Effective Response')
ax2b.fill_between(years_therapy, effective_response, alpha=0.2, color='darkred')
ax2b.set_xlabel('Years of Therapy', fontsize=10)
ax2b.set_ylabel('Capacity / Sensitivity (%)', fontsize=10)
ax2b.set_title('Receptor Desensitization', fontsize=11, fontweight='bold')
ax2b.legend(fontsize=8)
ax2b.grid(True, alpha=0.3)

# ========== Row 3: Pulsatile Response & ML Model ==========

# Plot 3a: Early vs Late Therapy Pulsatile Response
ax3a = fig.add_subplot(gs[2, 0])
ax3a.plot(t_detailed, dopamine_pulsatile_early, 'g-', linewidth=2, label='Early Therapy (year 1-3)')
ax3a.plot(t_detailed, dopamine_pulsatile_late, 'r-', linewidth=2, label='Late Therapy (year 20+)')
ax3a.fill_between(t_detailed, dopamine_pulsatile_early, alpha=0.15, color='green')
ax3a.fill_between(t_detailed, dopamine_pulsatile_late, alpha=0.15, color='red')
ax3a.axhline(3, color='gray', linestyle='--', alpha=0.5, linewidth=1)
ax3a.set_xlabel('Time (hours)', fontsize=10)
ax3a.set_ylabel('Dopamine Release', fontsize=10)
ax3a.set_title('Pulsatile Response Decline', fontsize=11, fontweight='bold')
ax3a.legend(fontsize=9)
ax3a.grid(True, alpha=0.3)

# Plot 3b: Effect of MAO-B Inhibitors on Receptor Sensitivity
ax3b = fig.add_subplot(gs[2, 1])
ax3b.plot(years_therapy, effective_response, 'r-', linewidth=2.5, label='Standard Therapy')
ax3b.plot(years_therapy, effective_response_with_mao, 'b-', linewidth=2.5, label='+ MAO-B Inhibitor')
ax3b.fill_between(years_therapy, effective_response, alpha=0.2, color='red')
ax3b.fill_between(years_therapy, effective_response_with_mao, alpha=0.2, color='blue')
ax3b.set_xlabel('Years of Therapy', fontsize=10)
ax3b.set_ylabel('Effective Response (%)', fontsize=10)
ax3b.set_title('MAO-B Inhibitors: Slowing Decline', fontsize=11, fontweight='bold')
ax3b.legend(fontsize=9)
ax3b.grid(True, alpha=0.3)

# Plot 3c: ML Model - Symptom Score Prediction
ax3c = fig.add_subplot(gs[2, 2])
scatter = ax3c.scatter(years_on_therapy, symptom_score, alpha=0.6, s=80, c=dosage_mg, cmap='RdYlGn_r', edgecolor='black', linewidth=0.5)
ax3c.plot(years_range, y_pred, 'r-', linewidth=3, label=f'Polynomial Fit (R² = {r2:.3f})')
ax3c.set_xlabel('Years on Therapy', fontsize=10)
ax3c.set_ylabel('Symptom Score', fontsize=10)
ax3c.set_title(f'ML Model: Predicting Symptom Severity\n(Colored by Dosage)', fontsize=11, fontweight='bold')
ax3c.legend(fontsize=9)
ax3c.grid(True, alpha=0.3)
cbar = plt.colorbar(scatter, ax=ax3c)
cbar.set_label('Dosage (mg)', fontsize=9)

plt.savefig('parkinsons_advanced_kinetics.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# DETAILED OUTPUT & STATISTICS
# ============================================================================

print("=" * 80)
print("ADVANCED PARKINSON'S KINETICS MODEL - COMPREHENSIVE ANALYSIS")
print("=" * 80)

print(f"\n1. DOPAMINE KINETICS")
print(f"   Healthy steady-state [D]: {D_ss_healthy:.3f}")
print(f"   Parkinson's steady-state [D]: {D_ss_parkinsons:.3f}")
print(f"   Loss: {(1 - D_ss_parkinsons/D_ss_healthy)*100:.1f}%")

print(f"\n2. COMT INHIBITOR EFFICACY")
print(f"   L-DOPA half-life (alone): {t_half_ldopa} hour")
print(f"   L-DOPA half-life (+ COMT): {t_half_with_comt} hours")
print(f"   Duration extension: {(t_half_with_comt/t_half_ldopa - 1)*100:.1f}%")
if osc_alone > 0:
    print(f"   Oscillation reduction: {(1 - osc_with_comt/osc_alone)*100:.1f}%")
else:
    print(f"   Oscillation reduction: Smooth delivery achieved")

print(f"\n3. CONTINUOUS INFUSION vs PULSATILE")
print(f"   Pulsatile mean [L-DOPA]: {np.mean(C_pulsatile):.2f} | Std: {np.std(C_pulsatile):.2f}")
print(f"   Infusion mean [L-DOPA]: {np.mean(C_continuous_infusion):.2f} | Std: {np.std(C_continuous_infusion):.2f}")
print(f"   Stability improvement: {(1 - np.std(C_continuous_infusion)/np.std(C_pulsatile))*100:.1f}%")

print(f"\n4. RECEPTOR DESENSITIZATION & STORAGE")
print(f"   Initial effective response: 100%")
print(f"   Year 10 (standard therapy): {effective_response[np.argmin(np.abs(years_therapy - 10))]:.1f}%")
print(f"   Year 20 (standard therapy): {effective_response[np.argmin(np.abs(years_therapy - 20))]:.1f}%")
print(f"   Year 10 (+ MAO-B inhibitor): {effective_response_with_mao[np.argmin(np.abs(years_therapy - 10))]:.1f}%")
print(f"   Year 20 (+ MAO-B inhibitor): {effective_response_with_mao[np.argmin(np.abs(years_therapy - 20))]:.1f}%")
print(f"   Neuroprotection benefit: {effective_response_with_mao[np.argmin(np.abs(years_therapy - 20))] - effective_response[np.argmin(np.abs(years_therapy - 20))]:.1f}% at year 20")

print(f"\n5. PULSATILE RESPONSE DYNAMICS")
peak_early = np.max(dopamine_pulsatile_early)
peak_late = np.max(dopamine_pulsatile_late)
print(f"   Peak dopamine (early therapy): {peak_early:.2f}")
print(f"   Peak dopamine (late therapy): {peak_late:.2f}")
print(f"   Response amplitude decline: {(1 - peak_late/peak_early)*100:.1f}%")

print(f"\n6. MACHINE LEARNING MODEL")
print(f"   Model type: Polynomial Regression (degree 2)")
print(f"   Training samples: {n_samples}")
print(f"   Features: [Years on Therapy, Dosage (mg), Age]")
print(f"   R² Score: {r2:.4f}")
print(f"   Prediction accuracy: Good fit for clinical decision support")
print(f"\n   Example predictions:")
for y_pred_val, year in zip(y_pred[::10], years_range[::10]):
    print(f"     Year {year:.1f}: Predicted Symptom Score = {y_pred_val:.1f}/100")

print("=" * 80)